/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ethervisu_monitors_PcapMonitor */

#ifndef _Included_ethervisu_monitors_PcapMonitor
#define _Included_ethervisu_monitors_PcapMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ethervisu_monitors_PcapMonitor
 * Method:    runMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ethervisu_monitors_PcapMonitor_runMonitor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
